name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: go.mod

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: go.mod

    - name: Format code
      run: go fmt ./...

    - name: Check formatting
      run: |
        if ! git diff --exit-code; then
          echo "Code is not formatted correctly. Please run 'go fmt ./...' and commit the changes."
          exit 1
        fi
